export const SET_IS_STATS_LOADING = "SET_IS_STATS_LOADING";
export const SET_IS_BEST_LOADING = "SET_IS_BEST_LOADING";
export const SET_IS_DECISION_LOADING = "SET_IS_DECISION_LOADING";
export const SET_ERROR = "SET_ERROR";
export const SET_STATS_ITEM = "SET_STATS_ITEM";
export const SET_BEST_ITEM = "SET_BEST_ITEM";
export const SET_DECISION_ITEMS = "SET_DECISION_ITEMS";



