export const SET_IS_INFO_LOADING = "SET_IS_INFO_LOADING";
export const SET_IS_SOLVED_TASKS_LOADING = "SET_IS_SOLVED_TASKS_LOADING";
export const SET_IS_UNRESOLVED_TASKS_LOADING = "SET_IS_UNRESOLVED_TASKS_LOADING";
export const SET_IS_BEST_SOLUTIONS_TASKS_LOADING = "SET_IS_BEST_SOLUTIONS_TASKS_LOADING";
export const SET_ALL_TRUE = "SET_ALL_TRUE";


export const SET_ERROR = "SET_ERROR";

export const SET_INFO = "SET_INFO";
export const SET_SOLVED_TASKS = "SET_SOLVED_TASKS";
export const SET_UNRESOLVED_TASKS = "SET_UNRESOLVED_TASKS";
export const SET_BEST_SOLUTIONS_TASKS = "SET_BEST_SOLUTIONS_TASKS";



