export const SET_INPUT_VALUE_SQL = "SET_INPUT_VALUE_SQL";
export const SET_IS_EXECUTING_SQL = "SET_IS_EXECUTING_SQL";
export const SET_ERROR_EXECUTING_SQL = "SET_ERROR_EXECUTING_SQL";
export const SET_SQL_ITEMS = "SET_SQL_ITEMS";

export const SET_CHECK_SELECT = "SET_CHECK_SELECT";
export const SET_IS_CHECKING_SELECT = "SET_IS_CHECKING_SELECT";
export const SET_ERROR_CHECKING_SELECT = "SET_ERROR_CHECKING_SELECT";
export const SET_CHECK_RESULT = "SET_CHECK_RESULT_CHECK";


